SELECT MONTHS_BETWEEN('14/09/30', '14/08/31')
FROM DUAL;

SELECT MONTHS_BETWEEN('14/08/31', '14/09/30')
FROM DUAL;

SELECT SYSDATE
, ADD_MONTHS(SYSDATE, 1)
, ADD_MONTHS(SYSDATE, 3)
, ADD_MONTHS('16/12/31', 2)
FROM DUAL;

SELECT SYSDATE
, NEXT_DAY(SYSDATE, 'FRI')
, NEXT_DAY(SYSDATE, 'SUN')
, NEXT_DAY(SYSDATE, 'SAT')

FROM DUAL;

SELECT SYSDATE
, LAST_DAY(SYSDATE)
, LSAT_DAY('11/11/11')
FROM DUAL;
