SELECT * FROM CAL;

CREATE TABLE CAL2 (
    SUN INT,
    MON INT,
    TUE INT,
    WED INT,
    THU INT,
    FRI INT,
    SAT INT
    );
--MON, TUE, WED, THU, FRI, SAT
INSERT INTO CAL2(SUN)
SELECT DAYNO FROM CAL
        WHERE DAY = 'SUN'
        ;
INSERT INTO CAL2(MON)
SELECT DAYNO FROM CAL
        WHERE DAY = 'MON'
        ;
INSERT INTO CAL2(TUE)
SELECT DAYNO FROM CAL
        WHERE DAY = 'TUE'
        ;
INSERT INTO CAL2(WED)
SELECT DAYNO FROM CAL
        WHERE DAY = 'WED'
        ;
INSERT INTO CAL2(THU)
SELECT DAYNO FROM CAL
        WHERE DAY = 'THU'
        ;
INSERT INTO CAL2(FRI)
SELECT DAYNO FROM CAL
        WHERE DAY = 'FRI'
        ;
INSERT INTO CAL2(SAT)
SELECT DAYNO FROM CAL
        WHERE DAY = 'SAT'
        ;

UPDATE CAL2
SET MON = (SELECT DAYNO FROM CAL
        WHERE DAY = 'MON');

SELECT * FROM CAL2;

ALTER TABLE CAL1
DROP COLUMN SUN;
ALTER TABLE CAL
ADD SUN INT;

INSERT INTO CAL

DESC CAL;
SELECT * FROM CAL;