SELECT ENAME
, DEPTNO
, INITCAP(ENAME)
FROM EMP
WHERE DEPTNO = 10;

SELECT NAME
, LOWER(NAME)
, UPPER(NAME)
FROM PROFESSOR;

SELECT ENAME
, LENGTH(ENAME)
, LENGTHB(ENAME)
FROM EMP;

SELECT '서진수'
,LENGTH('서진수')
,LENGTHB('서진수')
FROM DUAL;

SELECT ENAME
, JOB
, CONCAT(ENAME, JOB)
, ENAME || JOB
FROM EMP;

SELECT JOB
, SUBSTR(JOB,1,3)
, SUBSTR(JOB,2)
, SUBSTR(JOB,-3,3)
FROM EMP;

SELECT * FROM STUDENT;
SELECT NAME
,SUBSTR(JUMIN,3,4) "태어난 월일"
,DEPTNO1
FROM STUDENT
WHERE DEPTNO1 = 101;

SELECT '서진수'
, SUBSTR('서진수',1,3)
, SUBSTRB('서진수',1,3)
FROM DUAL;

SELECT 'A-B-C-D'
,INSTR('A-B-C-D','-',-3,1)
,INSTR('A-B-C-D','-',-1,3)
,INSTR('A-B-C-D','-',-6,1)
,INSTR('A-B-C-D','-',1,3)
,INSTR('A-B-C-D','-',3,1)
,INSTR('A-B-C-D','-',3)
,INSTR('A-B-C-D','-')
,INSTR('A-B-C-D','C')
,INSTR('A-B-C-D','-',-3,1)
,INSTR('A-B-C-D','-',-1,3)
,INSTR('A-B-C-D','-',-6,1)
FROM DUAL;

SELECT * FROM STUDENT;
SELECT NAME
, TEL
, INSTR(TEL,')')
, INSTR(TEL,')',1,1)
, INSTR(TEL,')',1)
FROM STUDENT
WHERE DEPTNO1 = 201;

SELECT NAME
,TEL
,INSTR(TEL,8,1,2)
FROM STUDENT
WHERE DEPTNO1 = 101;