SELECT * FROM STUDENT;
SELECT NAME
, TEL
, SUBSTR(TEL,1,(INSTR(TEL,')')-1))
FROM STUDENT
WHERE DEPTNO1 = 201;

SELECT NAME
, ID
, RPAD(ID, 10, '*')
FROM STUDENT;

SELECT LPAD(ENAME, 9, 123456789)
FROM EMP
WHERE DEPTNO = 10;

SELECT RPAD(ENAME, 10, '-')
FROM EMP
WHERE DEPTNO = 10;

SELECT RPAD(ENAME, 9, SUBSTR(123456789, LENGTH(ENAME) + 1))
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME
, LTRIM(ENAME, 'C')
, RTRIM(ENAME, 'R')
, REPLACE(ENAME, SUBSTR(ENAME, 1, 2), '**')
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME
, REPLACE(ENAME, SUBSTR(ENAME, 2, 2), '--*')
FROM EMP
WHERE DEPTNO = 20;

SELECT NAME
, JUMIN
, REPLACE(JUMIN, SUBSTR(JUMIN, 7, 7), '-/-/-/-')
FROM STUDENT;

SELECT NAME
, TEL
, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, ')') + 1, 3), '***')
FROM STUDENT
WHERE DEPTNO1 = 102;

SELECT NAME
, TEL
, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, '-') + 1, 5), '****') 
FROM STUDENT
WHERE DEPTNO1 = 101;