SELECT * FROM EMP;

SELECT ENAME "이름"
     , JOB 직업
     , HIREDATE 입사일 
    FROM EMP;

SELECT HIREDATE DESC FROM EMP "사원 정보";

DESC EMP;

SELECT * FROM EMP;

SELECT EMPNO, ENAME, JOB FROM EMP;

SELECT DISTINCT DEPTNO FROM EMP;

SELECT ENAME || '의 입사일은 ' || HIREDATE || '이고, 급여는 $' || SAL || '이다' FROM EMP; 

SELECT * FROM EMP;

SELECT ENAME, JOB, SAL, SAL * 12  FROM EMP; 
