SELECT INITCAP('abcd') from dual;
SELECT LOWER('ABCED') FROM DUAL;
SELECT LENGTHB('ABCD') FROM DUAL;
SELECT CONCAT;
SELECT SUBSTR('ABCD',3,2) FROM DUAL;
SELECT INSTR('ABCD','C') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(1234,'0999999') FROM DUAL;
SELECT * FROM EMP;
SELECT AVG(SAL) FROM EMP;
SELECT * FROM PROFESSOR;
SELECT * FROM ;

SELECT NAME
FROM STUDETN LEFT OUTER JOIN PROFESSOR
ON;

CREATE TABLE WHATTHE(
EMPNO NUMBER(4)
ENAME VARCHAR(10)
);