SELECT * FROM STUDENT;
SELECT NAME, GRADE, HEIGHT FROM STUDENT
WHERE HEIGHT > 170
ORDER BY HEIGHT DESC;

SELECT DEPTNO1, NAME, ID, GRADE
FROM STUDENT
WHERE DEPTNO1 = 101 
AND GRADE >= 3;

SELECT NAME, GRADE, HEIGHT
FROM STUDENT
WHERE HEIGHT >=165
AND HEIGHT <=175
ORDER BY HEIGHT DESC;

SELECT NAME, ID, DEPTNO1
FROM STUDENT
WHERE NAME LIKE 'Bi%';

SELECT DEPTNO
FROM PROFESSOR
INTERSECT
SELECT DEPTNO
FROM DEPARTMENT
MINUS
SELECT DEPTNO1
FROM STUDENT;

SELECT * FROM PROFESSOR;

SELECT NAME, PAY, DEPTNO, BONUS
FROM PROFESSOR
WHERE BONUS IS NULL;

SELECT PROFNO, NAME, PAY, BONUS
FROM PROFESSOR
ORDER BY PAY DESC;

SELECT PROFNO, NAME, PAY, PAY*12 ¿¬ºÀ, DEPTNO
FROM PROFESSOR
ORDER BY DEPTNO ASC, PAY*12 DESC;

SELECT NAME, PAY, BONUS
FROM PROFESSOR
WHERE (PAY >= 300 AND BONUS IS NOT NULL)
OR (PAY >= 450);

SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;

SELECT PROFNO, NAME
FROM PROFESSOR
WHERE DEPTNO = 201
UNION
SELECT STUDNO, NAME
FROM STUDENT
WHERE DEPTNO1 = 201 OR DEPTNO2 = 201;