--연산자 종류: UNION, UNION ALL, INTERSECT, MINUS

--UNION: 합집합
SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO1=101
UNION ALL
SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO2=201;

--INTERSECT: 교집합
SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO1=101
INTERSECT
SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO2=201;

--MINUS: 차집합
SELECT EMPNO, ENAME, SAL FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL FROM EMP
WHERE SAL > 2500;