

SELECT * FROM EMP;
SELECT DEPTNO
     , SUM(DECODE(JOB, 'CLERK', 1,2)) "CLERK"
     , SUM(DECODE(JOB, 'MANAGER', 1,2)) "MANAGER"
     , SUM(DECODE(JOB, 'PRESIDENT', 1,2)) "PRESIDENT"
     , SUM(DECODE(JOB, 'ANALYST', 1,2)) "ANALYST"
     , SUM(DECODE(JOB, 'SALESMAN', 1,2)) "SALESMAN"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

PIVOT (
    SUM(SAL)
    FOR JOB
    IN ('CLERK', 'MANAGER', 'PRESIDENT', 'ANALYST', 'SALESMAN')
    );
    
    

SELECT EMPNO
        , DEPTNO
        , SAL
    FROM EMP;

SELECT EMPNO, 10, 20, 30
FROM (
    SELECT EMPNO, DEPTNO, SAL
    FROM EMP
)
PIVOT (
    MAX(SAL)
    FOR DEPTNO
    IN (10, 20, 30)
    );
    
SELECT DEPTNO
    , JOB
FROM EMP
ORDER BY DEPTNO;


