SELECT DEPTNO
        , JOB
        , SAL
    FROM EMP
    ORDER BY DEPTNO, JOB, SAL;

SELECT * 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='NEW_EMP2';

ROLLBACK;

ALTER TABLE NEW_EMP2
DROP CONSTRAINT SYS NEW_EMP2_LOCCODE_NN;

ALTER TABLE NEW_EMP2
MODIFY (LOC_CODE CONSTRAINT NEW_EMP2_LOCCODE_NN NOT NULL);

ALTER TABLE NEW_EMP2
ADD CONSTRAINT
NEW_EMP_NAME_UK UNIQUE(NAME);

ROLLBACK;
SELECT * FROM NEW_EMP2;
INSERT INTO NEW_EMP2 VALUES('1111','1',1,3,30);

CREATE TABLE NEW_EMP2
(NO NUMBER(4) PRIMARY KEY
,NAME VARCHAR2(20) NOT NULL
,JUMIN VARCHAR2(13) NOT NULL UNIQUE
,LOC_CODE NUMBER(1) CHECK(LOC_CODE<5) -- 5이상 못넣음
,DEPTNO NUMBER(2) REFERENCES DEPT(DEPTNO)
);

