SELECT * FROM STUDENT;

-- 4°Ç
SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO1=101;

SELECT STUDNO, NAME 
FROM STUDENT
WHERE DEPTNO2=201;

--12°Ç
SELECT EMPNO, ENAME, SAL FROM EMP;
--4°Ç
SELECT EMPNO, ENAME, SAL FROM EMP
WHERE SAL > 2500;